# Generated by Django 2.0.13 on 2019-11-13 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191113_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='teacherstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='core.Student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='students',
            field=models.ManyToManyField(through='core.TeacherStudent', to='core.Student'),
        ),
    ]
